### ISSUE TITLE
Can you add async validation for 3.9.0?

### ISSUE THREAD

**Issue by lxchurbakov** [akuzko/re-use-form#1]
Would love to see something like

```
defValidation('email-assigned', (value, { message }) => {
  return someApi.checkEmail(value).then(({ assigned }) => assigned ? Promise.reject(message || 'Email is assigned to someone else') : null);
});
```

**Comment by akuzko** [comment]
@swensson thanks for the issue, and sorry for late reply! the proposed feature is interesting, but requires a lot of things to consider under the hood. for instance, such async validations will not play well with automatic on-change validation (which by default happens if form has any errors on it). thus, I see it in the way of calling async validations only when `validate` helper (and other based on it) is called. and only if all "normal" validations have passed.

this new feature will require some additional validation configuration, but that definitely makes things more interesting. I'll look what can be done in nearest time

**Comment by akuzko** [comment]
@swensson must admit, it took some considerable effort. but final result looks pretty neat, I hope. Here's new release: https://github.com/akuzko/re-use-form/releases/tag/v3.9.0
